config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  resources :categories do
    resources :products
  end
end

app/models/album.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  image_url   :string
#  price       :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Album < ApplicationRecord
  has_many :tracks
  belongs_to :category

  validates :title, :description, :image_url, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged

  # eliminiates apostrophe
  def normalize_friendly_id(string)
    string.to_s.gsub("\'", "").parameterize
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :albums, -> { order(:created_at) }

  extend FriendlyId
  friendly_id :name, use: :slugged

  # eliminiates apostrophe
  def normalize_friendly_id(string)
    string.to_s.gsub("\'", "").parameterize
  end
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album

  def track_title
    RSpotify::Track.find(self.title)
  end

  def track_number
    track_title.track_number
  end

  def track_preview
    track_title.preview_url
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_category

  def show; end

  def new
    @album = Album.new
  end

  def create
    @category = @category.album.build(album_params)
    if @album.save
      flash[:notice] = "You have successfully added a new album!"
      redirect_to albums_url
    else
      flash[:alert] = "Oops, something went wrong. Couldn't add a new album!"
      render :new
    end
  end

  private

  def album_params
    params.require(:album).permit(:title, :description, :image_url, :price)
  end

  def set_category
    @category = Category.friendly.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_FLASH_MSG = {
    success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }

  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type.to_sym, flash_type.to_s)
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/views/albums/_form.html.haml
= form_for [@category, @album], url: { action: "create" }, html: { class: 'new-album-form' } do |f|
  - if @album.errors.any?
    #error_explanation
      %h2.text-center
        = pluralize(@album.errors.count, 'error')
        prohibited this album from being saved:
      %ul
      - @albums.errors.full_messages.each do |message|
        %li
          = message

  .container
    .row.justify-content-center
      .col-xs-12.col-lg-6
        .form-group
          = f.label :title
          = f.text_field :title, class: 'form-control'

        .form-group
          = f.label :description
          = f.text_area :description, rows: 10, cols: 60, class: 'form-control'

        .form-group
          = f.label :image_url
          = f.text_field :image_url, class: 'form-control'

        .form-group
          = f.label :price
          = f.text_field :price, class: 'form-control'

        .actions
          = f.submit

app/views/albums/new.html.haml
%h2.text-center
  Add a new product
= render 'form'

app/views/categories/index.html.haml
- @categories.each do |category|
  %article.product_category
    %header
      %h3= link_to category.name
    .container
      .products.row.justify-content-center
        - category.products.each do |product|
          .product.col
            = link_to image_tag(product.image_url, class: "img-responsive", id: "album_cover"), category_product_path(category, product)

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render 'layouts/shared/fonts'
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Depot
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/shared/header'
    = flash_messages
    = yield

app/views/layouts/shared/_fonts.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Lato:300,400,600,700", :rel => "stylesheet"}

app/views/layouts/shared/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => "#"} Navbar
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => "#"}
          Home
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{:href => "#"} Link
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Dropdown
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          %a.dropdown-item{:href => "#"} Action
          %a.dropdown-item{:href => "#"} Another action
          .dropdown-divider
          %a.dropdown-item{:href => "#"} Something else here
      %li.nav-item
        %a.nav-link.disabled{:href => "#"} Disabled